version: '3'
services:
  eureka-server:
    image: openjdk:17-jdk-slim
    container_name: eureka-server
    ports:
      - "8761:8761"
    volumes:
      - ./msexample/target:/app
    command: java -jar /app/msexample-0.0.1-SNAPSHOT.jar
    networks:
      - msnetwork

  order-service:
    image: openjdk:17-jdk-slim
    container_name: order-service
    ports:
      - "8081:8081"
    volumes:
      - ./msorder/target:/app
    command: java -jar /app/msorder-0.0.1-SNAPSHOT.jar
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - msnetwork
    depends_on:
      - eureka-server


  payment-service:
    image: openjdk:17-jdk-slim
    container_name: payment-service
    ports:
      - "8082:8082"
    volumes:
      - ./mspayment/target:/app
    command: java -jar /app/mspayment-0.0.1-SNAPSHOT.jar
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - msnetwork
    depends_on:
      - eureka-server

  api-gateway:
    image: openjdk:17-jdk-slim
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./gatewayexample/target:/app
    command: java -jar /app/gatewayexample-0.0.1-SNAPSHOT.jar
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - msnetwork
    depends_on:
      - eureka-server

networks:
  msnetwork:
    driver: bridge
